TrueJobs/TrueJobs/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TrueJobs;

namespace TrueJobs.Controllers
{
    public class ApplicationsController : Controller
    {
        private JobsEntities2 db = new JobsEntities2();

        // GET: Applications
        public ActionResult Index()
        {
            

             var applications = db.Applications.Include(a => a.User).Include(a => a.Job);
            
            return View(applications.ToList());
        }

        public ActionResult AplicarileMele(int id)
        {
            var app = db.Applications.Where(a => a.User_ID == id);

            return View(app.ToList());
        }


        public ActionResult SendEmail(string email, string jb)
        {


            if (ModelState.IsValid)
            {
                /*
                app.Job_ID = id;
                User user = db.Users.SingleOrDefault(s => s.Email == User.Identity.Name.TrimEnd());
                app.User_ID = user.User_ID;

                db.Applications.Add(app);
                db.SaveChanges();



                Job job = db.Jobs.SingleOrDefault(s => s.Job_ID == id);
                Company comp = db.Companies.SingleOrDefault(s => s.Company_ID == job.Company_ID);
                */

                string body = "Esti chemat la interviu pentru jobul " + jb+"!";
                string Body = "Esti chemat la interviu pentru jobul " + jb+ "!";
                string subject = "Invitatie la interviu";
                string Subject = "Invitatie la interviu";


                WebMail.SmtpServer = "smtp.gmail.com";
                //gmail port to send emails  
                WebMail.SmtpPort = 587;
                WebMail.SmtpUseDefaultCredentials = true;
                //sending emails with secure protocol  
                WebMail.EnableSsl = true;
                //EmailId used to send emails from application  
                WebMail.UserName = "truejobsproiect@gmail.com";
                WebMail.Password = "truejobsproiect@1234..";

                //Sender email address.  
                WebMail.From = "truejobsproiect@gmail.com";

                //Send email  
                WebMail.Send(to: email, subject: subject, body: body, cc: "", bcc: "", isBodyHtml: true);
                ViewBag.Status = "Email Sent Successfully.";

            }






            return Content("<script language='javascript' type='text/javascript'>alert('Ai trimis emailul'); window.location.href = 'http://localhost:50961/Jobs/Index/' ;</script>");
        }


        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "FirstName");
            ViewBag.Job_ID = new SelectList(db.Jobs, "Job_ID", "Name");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Application_ID,Job_ID,User_ID")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "FirstName", application.User_ID);
            ViewBag.Job_ID = new SelectList(db.Jobs, "Job_ID", "Name", application.Job_ID);
            return View(application);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "FirstName", application.User_ID);
            ViewBag.Job_ID = new SelectList(db.Jobs, "Job_ID", "Name", application.Job_ID);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Application_ID,Job_ID,User_ID")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "FirstName", application.User_ID);
            ViewBag.Job_ID = new SelectList(db.Jobs, "Job_ID", "Name", application.Job_ID);
            return View(application);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = db.Applications.Find(id);
            db.Applications.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrueJobs/TrueJobs/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrueJobs;

namespace TrueJobs.Controllers
{
    public class UsersController : Controller
    {
        private JobsEntities2 db = new JobsEntities2();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(/*int? id,*/ string email)
        {
            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //User user = db.Users.Find(id);
            User user = db.Users.SingleOrDefault(d => d.Email == email);
            ViewBag.userID = user.User_ID;
            WriteCV wrcv = db.WriteCVs.SingleOrDefault(d=> d.User_ID == user.User_ID);
            ViewBag.writecv = wrcv.WritecvID;
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file2, CV cv, IEnumerable<HttpPostedFileBase> files, User user)
        {

            if (file2 != null && file2.ContentLength > 0)
            {
                // extract only the filename
                var fileName = Path.GetFileNameWithoutExtension(file2.FileName) + " _ " + DateTime.Now.ToString("ddHmmss") + Path.GetExtension(file2.FileName);
               
                var path = Path.Combine(Server.MapPath("~/imgpoze"), fileName);
                user.Photo = fileName;

                file2.SaveAs(path);
            }

            if (ModelState.IsValid)
            {
                user.Email = User.Identity.Name.TrimEnd();
                db.Users.Add(user);
                db.SaveChanges();

                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName_att = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName_att);
                        cv.CV_path = fileName_att;
                        cv.User_ID = user.User_ID;
                        file.SaveAs(path);


                        db.CVs.Add(cv);
                        db.SaveChanges();

                    }
                }

                return RedirectToAction("Create2", new { id = user.User_ID});
            }

            return View(user);
        }


        public ActionResult Create2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.Tag_ID = new SelectList((from p in db.Interests
                                             select new
                                             {
                                                 Tag_ID1 = p.Interest_ID,
                                                 Tag_name1 = p.Name
                                             }), "Tag_ID1", "Tag_name1");

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create2(User user, Users_interests user_interest)
        {

            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Success");
            }
            ViewBag.Tag_ID = new SelectList((from p in db.Interests
                                             select new
                                             {
                                                 Tag_ID1 = p.Interest_ID,
                                                 Tag_name1 = p.Name
                                             }), "Tag_ID1", "Tag_name1");
            return View(user);
        }


        public JsonResult AddTag(int id, int elem)
        {
         
            var tag = new Users_interests();

            //set student name

            tag.User_ID = elem;
            tag.Interest_ID = id;


            //create DBContext object
            //Add Student object into Students DBset
            db.Users_interests.Add(tag);

          
            db.SaveChanges();



            return Json(new { success = true }, JsonRequestBehavior.AllowGet);

        }
        //public JsonResult DeleteTag(int id, int elem)
        //{
        //    Articles_tags tagToDelete = new Articles_tags();
        //    tagToDelete.ID_Art = elem;
        //    tagToDelete.Tag_ID = id;
        //    db.Entry(tagToDelete).State = System.Data.Entity.EntityState.Deleted;
        //    db.SaveChanges();

        //    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        //}
        public JsonResult DeleteTag(int id)
        {
            Interest tag = db.Interests.Find(id);
            Users_interests tagToDelete = db.Users_interests.Where(a => a.Interest_ID == tag.Interest_ID).FirstOrDefault();
            db.Users_interests.Remove(tagToDelete);
            db.SaveChanges();


            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }



        [ActionName("userinterest")]
        public ActionResult UserInterest(int id)
        {


            User user = db.Users.Find(id);
            IEnumerable<Interest> model = from p in db.Interests
                                     join pe in db.Users_interests on p.Interest_ID equals pe.Interest_ID
                                     where pe.User_ID == user.User_ID
                                     select p;           
            return View(model);

        }
        [ActionName("userinterest2")]
        public ActionResult UserInterest2(string email)
        {
            User user = db.Users.SingleOrDefault(d=>d.Email==email);
            IEnumerable<Interest> model = from p in db.Interests
                                          join pe in db.Users_interests on p.Interest_ID equals pe.Interest_ID
                                          where pe.User_ID == user.User_ID
                                          select p;
            return View(model);
        }


        public ActionResult Downloads(int id = 0)
        {
            var fileToRetrieve = db.CVs.Where(f => f.User_ID == id);
            return View(fileToRetrieve);
        }

        public FileResult Download(string name)
        {

            var path = "~/App_Data/uploads/" + name;
            return File(path, "application/force-download", Path.GetFileName(path));

        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "User_ID,FirstName,LastName,Email,Phone,Photo,Location,Experience")] */User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(/*int? id*/ string email)
        {
            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.SingleOrDefault(d => d.Email == email);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(/*int id*/ string email)
        {
            User user = db.Users.SingleOrDefault(d => d.Email == email);

            db.CVs.RemoveRange(db.CVs.Where(c => c.User_ID == user.User_ID));
            db.Users_interests.RemoveRange(db.Users_interests.Where(c=>c.User_ID == user.User_ID));
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrueJobs/TrueJobs/Views/Users/Create2.cshtml
@model TrueJobs.User

@{
    ViewBag.Title = "Create2";

}

<head>


    @*<link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/Site.css" rel="stylesheet" />*@
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <style>
        body {
            background-image: linear-gradient(rgba(0, 142, 99, 0.1), rgba(0, 0, 0, 0.1)), url('../../Content/img_biz/1.jpg');
            background-size: cover;
            background-attachment: fixed;
        }
    </style>

</head>
<script src="~/Scripts/jquery.min.js"></script>

<body>
    @*    <div class="wrapper">

        <div class="content-wrapper">
            <section class="content">*@


    <br />
    <br />
    <br />
    <br />


    <main id="main" style="margin-top:100px">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="container">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-8">
                        <div class="form-horizontal">
                            <h2>Selecteaza domeniile de interes</h2>
                            <hr />



                            <br />
                            <br />

                            <br />
                            <br />
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.User_ID)
                            @Html.HiddenFor(model => model.FirstName)
                            @Html.HiddenFor(model => model.LastName)
                            @Html.HiddenFor(model => model.Experience)
                            @Html.HiddenFor(model => model.Photo)




                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-10">
                                        @Html.DropDownList("Tag_ID", ViewBag.Tag_ID as SelectList, "Select domeniile de interes", htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Users_interests, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="col-lg-2">
                                        <button type="button" class="btn btn-default " onclick="AddTag()">Add</button>
                                    </div>
                                </div>
                            </div>

                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12" id="competence-tags-div">
                                        @Html.Action("UserInterest")
                                    </div>
                                </div>
                            </div>
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <div class="form-group">
                                @*<button type="button" class="btn btn-default " style="color:white" onclick="location.href='@Url.Action("Details", "Users", new { email = Model.Email.TrimEnd() })'" data-dismiss="modal">Finish</button>*@
                                <button type="button" class="btn btn-default" style="color:white" onclick="location.href='@Url.Action("Create", "WriteCVs")'">Pasul 4</button>
                            </div>

                        </div>
                    </div>
                    <div class="col-lg-2"></div>
                </div>
            </div>
        }



        @*</section>
                </div>
            </div>*@


    </main>
    <script>
        function AddTag() {
            var e = document.getElementById("Tag_ID");

            if (e.options[e.selectedIndex].value != "") {
                //alert(e.options[e.selectedIndex].value);
                $.ajax({
                    type: 'POST',
                    data: { id: e.options[e.selectedIndex].value, elem: @Model.User_ID }, // #2
                    url: '/Users/AddTag/',
                    //contentType: 'application/json', #3
                    //dataType: 'json', #2
                    //alert("ceva");
                    success: function () {
                        $.get('@Url.Action("UserInterest", "Users")', {}, function (response) {
                           alert('yuhuhu');
                            $("#competence-tags-div").html(response);
                        });
                        location.reload();
                    },

                    error: function () {
                        alert('not good');
                    }
                });
            }
        };
    </script>
</body>

TrueJobs/TrueJobs/Views/Users/Delete.cshtml
@model TrueJobs.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TrueJobs/TrueJobs/Views/Users/Details.cshtml
@model TrueJobs.User

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    <link href="~/Content/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            background-image: linear-gradient(rgba(0, 142, 99, 0.1), rgba(0, 0, 0, 0.1)), url('../../Content/img_biz/1.jpg');
            background-size: cover;
            background-attachment: fixed;
        }

        a:hover {
            text-decoration: none;
        }
    </style>
</head>
@*@if (User.Identity.IsAuthenticated)
    {*@
<body>
    @*    <div class="wrapper">

        <div class="content-wrapper">
            <section class="content">*@


    <br />
    <br />
    <br />


    <main id="main" style="margin-top:100px">




        <section class="content">


            <h3>Profilul meu</h3>
            <div class="row">
                <div class="col-md-3">
                    <div class="  box box-primary">
                        <div class=" box-body box-profile ">
                            <img class="profile-user-img img-responsive img-circle" src="~/imgpoze/@Model.Photo" alt="User picture">

                            <h3 class="profile-username text-center">@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h3>



                            
                            
                                    @if (User.IsInRole("candidat"))
                                    {
                                        <a href="@Url.Action("Edit", "Users", new { id = ViewBag.userID })" class="btn btn-default"><b>Edit profile</b></a>
                                    }
                                
                             
                                    <a href="@Url.Action("Details", "WriteCVs", new { id = ViewBag.writecv })" class="btn btn-default"><b>View CV</b></a>

                            
                                    <a href="@Url.Action("SetPassword", "Manage")" class="btn btn-default" style="margin-top:15px"><b>Change password</b></a>

                                
                     







                            @*<ul class="list-group list-group-unbordered">
                                    <li class="list-group-item">
                                        <b>Created by</b> <p class="pull-right">@Html.DisplayFor(model => model.Author)</p>
                                    </li>
                                    <li class="list-group-item">
                                        <b>Date</b> <p class="pull-right">@Html.DisplayFor(model => model.Date)</p>
                                    </li>

                                </ul>*@
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->



                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Detalii</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <strong><i class="fa fa-book margin-r-5"></i> CV</strong>

                            <br><br>
                            @foreach (var item in Model.CVs)
                            {
                                if (item.CV_path.Length > 10)
                                {
                                    string parameterValue = item.CV_path.Substring(0, 10) + "... ";
                                    string pat = '.' + item.CV_path.Substring(item.CV_path.ToString().LastIndexOf('.') + 1);
                                    parameterValue += pat;

                                    @Html.DisplayFor(modelItem => parameterValue)
                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => item.CV_path)
                                }
                                <div class="pull-right">
                                    @Html.ActionLink(" ", "Download", new { name = @item.CV_path }, new { @class = "glyphicon glyphicon-download-alt" })
                                </div>

                                <br><br>
                            }


                            <hr>
                            <strong><i class="fa fa-pencil margin-r-5"></i>Domenii de interes</strong>
                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.Action("UserInterest2")
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>


                </div>




                <div class="col-md-9">

                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li class=""><a href="#activity" data-toggle="tab">Informatii</a></li>
                            @if (User.IsInRole("candidat"))
                            {
                                <li><a href="#timeline" data-toggle="tab">Aplicarile mele</a></li>
                            }
                        </ul>
                        <div class="tab-content">
                            <div class="active tab-pane" id="activity">
                                <br />

                                <div class="row post">

                                    <div class="col-md-4"></div>
                                    <div class="col-md-4">

                                        <h4>Email: @Model.Email</h4>
                                        <h4>Telefon: @Model.Phone</h4>
                                        <h4>Judet: @Model.County</h4>
                                        <h4>City: @Model.City</h4>
                                        <h4>Experienta: @Model.Experience ani</h4>
                                    </div>
                                    <div class="col-md-4"></div>


                                </div>




                                <!-- /.post -->
                            </div>
                            <!-- /.tab-pane -->
                            <div class="tab-pane" id="timeline">
                                <!-- The timeline -->
                                <p>ceva</p>

                                @Html.Action("AplicarileMele", "Applications", new { ID = Model.User_ID })

                            </div>
                            <!-- /.tab-pane -->
                            <!-- /.tab-pane -->
                        </div>
                        <!-- /.tab-content -->
                    </div>







                </div>


            </div>
        </section>

        <br />
        <br />
        <br />




    </main>
</body>
@*}*@
@*<div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Photo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Photo)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.Experience)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Experience)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.User_ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@