TrueJobs/TrueJobs/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrueJobs;
using PagedList;

using System.Net;
using System.Net.Mail;
using System.Web.Helpers;

namespace TrueJobs.Controllers
{
    public class JobsController : Controller
    {
        private JobsEntities2 db = new JobsEntities2();

        // GET: Jobs
        public ActionResult Index(string sortOrder, string searchString, string experience,
            string currentFilter, string Interest, string Location, int? page)
        {


            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "RecordName" ? "date_desc" : "RecordName";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;



            var jobs = from s in db.Jobs.Include(p => p.Company).Include(p => p.Interest).Include(p => p.Applications)
                       select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                // query = query.Where(s => s.Title.Contains(searchString));
                //words = words.Where(s => s.Title.Contains(searchString));
                jobs = jobs.Where(s => s.Name.Contains(searchString));

                /*
                var jobs = (from m in db.Jobs
                              where m.Name == searchString
                              select m).FirstOrDefault();
                */
            }

            if (!string.IsNullOrEmpty(experience))
            {
                // query = query.Where(s => s.Title.Contains(searchString));
                //words = words.Where(s => s.Title.Contains(searchString));
                jobs = jobs.Where(s => s.Experience.ToString().Contains(experience));

                /*
                var produs = (from m in db.Jobs
                              where m.Name == searchString
                              select m).FirstOrDefault();
                */
            }

            if (!String.IsNullOrEmpty(Interest))
            {
                int IDInterest = Int32.Parse(Interest);

                jobs = from e in jobs
                       join de in db.Interests on e.Interest_ID equals de.Interest_ID
                       where de.Interest_ID == IDInterest
                       select e;
                //ViewBag.EmpSel = Employee;

            }

            IEnumerable<Interest> inte = db.Interests.ToList();
            ViewBag.Interest = inte;

            if (!String.IsNullOrEmpty(Location))
            {
                jobs = jobs.Where(s => s.Location.Contains(Location));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    //words = words.OrderByDescending(s => s.Title);
                    jobs = jobs.OrderByDescending(s => s.Name);
                    // model = model.OrderByDescending(s => s.Tag_name);

                    break;
                default:  // Name ascending 		
                          // words = words.OrderBy(s => s.Word);
                    jobs = jobs.OrderBy(s => s.Name);
                    // model = model.OrderBy(s => s.Tag_name);
                    break;
            }


            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(jobs.ToPagedList(pageNumber, pageSize));
            /*
            var jobs = db.Jobs.Include(j => j.Company).Include(j => j.Interest);
            return View(jobs.ToList());
            */
        }


        public ActionResult JobList()
        {
            return View();
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);


            Company com = db.Companies.SingleOrDefault(d => d.Company_ID == job.Company_ID);

            ViewBag.emailcompanie = com.Email;
            ViewBag.telefon = com.Phone;
            ViewBag.nume = com.Name;

            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.Company_ID = new SelectList(db.Companies, "Company_ID", "Name");
            ViewBag.Interest_ID = new SelectList(db.Interests, "Interest_ID", "Name");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job)
        {



            if (ModelState.IsValid)
            {
                var email = User.Identity.Name;
                Company company = db.Companies.SingleOrDefault(d => d.Email == email);
                job.Company_ID = company.Company_ID;

                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Details", "Companies", new { email = User.Identity.Name.TrimEnd() });
            }





            ViewBag.Company_ID = new SelectList(db.Companies, "Company_ID", "Name", job.Company_ID);
            ViewBag.Interest_ID = new SelectList(db.Interests, "Interest_ID", "Name", job.Interest_ID);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.Company_ID = new SelectList(db.Companies, "Company_ID", "Name", job.Company_ID);
            ViewBag.Interest_ID = new SelectList(db.Interests, "Interest_ID", "Name", job.Interest_ID);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Job_ID,Name,Location,Description,Requirements,Type,Interest,Experience,Company_ID,Interest_ID,Attributes")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                // return RedirectToAction("Index");
                return RedirectToAction("Details", "Companies", new { email = User.Identity.Name.TrimEnd() });
            }
            ViewBag.Company_ID = new SelectList(db.Companies, "Company_ID", "Name", job.Company_ID);
            ViewBag.Interest_ID = new SelectList(db.Interests, "Interest_ID", "Name", job.Interest_ID);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Details", "Companies", new { email = User.Identity.Name.TrimEnd() });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult CompanyJobs(int id, string sortOrder, string searchString,
            string currentFilter, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "RecordName" ? "date_desc" : "RecordName";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;



            var jobs = from s in db.Jobs
                       select s;

            jobs = jobs.Where(s => s.Company_ID == id);

            switch (sortOrder)
            {
                case "name_desc":
                    //words = words.OrderByDescending(s => s.Title);
                    jobs = jobs.OrderByDescending(s => s.Name);
                    // model = model.OrderByDescending(s => s.Tag_name);

                    break;
                default:  // Name ascending 		
                          // words = words.OrderBy(s => s.Word);
                    jobs = jobs.OrderBy(s => s.Name);
                    // model = model.OrderBy(s => s.Tag_name);
                    break;
            }


            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(jobs.ToPagedList(pageNumber, pageSize));



        }





        public ActionResult SimilarJobs(int id, string sortOrder, string searchString,
            string currentFilter, int? page)

TrueJobs/TrueJobs/Views/Jobs/CompanyJobs.cshtml
@*@model IEnumerable<TrueJobs.Job>*@

@model PagedList.IPagedList<TrueJobs.Job>
@using PagedList.Mvc;

@{
    Layout = null;
}
@{
    ViewBag.Title = "CompanyJobs";
}

<h2>My Jobs</h2>


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Location
        </th>
       
        <th>
            Type
        </th>
        <th>
            Experience
        </th>
       
        <th>
            Company Name
        </th>
        <th>
            Interest Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
          
            
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Experience)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Company.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Interest.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Job_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.Job_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Job_ID })
            </td>
        </tr>
    }

</table>

@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)din @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("CompanyJobs",
                                                                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilter2 = ViewBag.Taguri }))

TrueJobs/TrueJobs/Views/Jobs/Details.cshtml
@model TrueJobs.Job

@{
    ViewBag.Title = "Details";
}


<head>
    <link href="~/Content/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            background-image: linear-gradient(rgba(0, 142, 99, 0.1), rgba(0, 0, 0, 0.1)), url('../../Content/img_biz/1.jpg');
            background-size: cover;
            background-attachment: fixed;
        }

        a:hover {
            text-decoration: none;
        }
    </style>

</head>



<main id="main" style="margin-top:100px">

    <br />
    <br />
    <br />


    <section class="content">


        <h3>@Model.Name</h3>

        @if (User.Identity.IsAuthenticated) { 
        <a href="@Url.Action("Aplica", "Jobs", new { id = Model.Job_ID})" class="btn btn-default"><b>Aplica la job</b></a>
        
        }
        <br />
        <br />
        <div class="row">
            <div class="col-md-3">


                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Detalii</h3>
                    </div>


                    <div class="box-body">
                        <strong><i class="fa fa-location-arrow margin-r-5"></i>Locatie</strong>
                        <div class="form-group">
                            <div class="col-md-12">
                                <p> @Model.Location</p>
                            </div>
                        </div>

                        <hr>
                        <strong><i class="fa fa-phone margin-r-5"></i>Nume companie</strong>
                        <div class="form-group">
                            <div class="col-md-12">
                                <p>@ViewBag.nume</p>
                            </div>
                        </div>

                        <hr>
                        <strong><i class="fa fa-envelope margin-r-5"></i>Email companie</strong>
                        <div class="form-group">
                            <div class="col-md-12">
                                <p>@ViewBag.emailcompanie</p>
                            </div>
                        </div>
                        <hr>
                        <strong><i class="fa fa-phone margin-r-5"></i>Telefon companie</strong>
                        <div class="form-group">
                            <div class="col-md-12">
                                <p>@ViewBag.telefon</p>
                            </div>
                        </div>



                    </div>
                    <!-- /.box-body -->
                </div>



            </div>

            <div class="col-md-9">

                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class=""><a href="#activity" data-toggle="tab">Detalii job</a></li>
                        <li><a href="#timeline" data-toggle="tab">Joburi similare</a></li>

                    </ul>

                    <div class="tab-content">
                        <div class="active tab-pane" id="activity">
                            <p><b>Interes</b></p> <br />
                            <p>@Model.Interest.Name</p>
                            <p><b>Descriere</b></p> <br />
                            <p>@Model.Description</p>
                            <br />
                            <p><b>Cerinte</b></p> <br />
                            <p>@Model.Requirements</p>
                            <p><b>Tip</b></p> <br />
                            <p>@Model.Type</p>
                            <p><b>Experienta necesara</b></p> <br />
                            <p>@Model.Experience</p>
                            <p><b>Atribute</b></p> <br />
                            <p>@Model.Attributes</p>
                        </div>

                        <div class="tab-pane" id="timeline">
                          

                            @Html.Action("SimilarJobs", "Jobs", new { ID = Model.Job_ID })
                        </div>

                    </div>
                </div>
            </div>




    </section>
</main>

@*<div>
        <h4>Job</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Requirements)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Requirements)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Interest)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Interest)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Experience)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Experience)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Attributes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Attributes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Company.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Company.Name)
            </dd>



        </dl>
    </div>*@
@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Job_ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

TrueJobs/TrueJobs/Views/Jobs/Index.cshtml
@*@model IEnumerable<TrueJobs.Job>*@


@model PagedList.IPagedList<TrueJobs.Job>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";

    List<SelectListItem> listItems2 = new List<SelectListItem>();


    listItems2.Add(new SelectListItem
    {
        Text = "Alba Iulia",

    });
    listItems2.Add(new SelectListItem
    {
        Text = "Arad"

    });
    listItems2.Add(new SelectListItem
    {
        Text = "Pitești"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Bacău"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Oradea"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Bistrița"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Botoșani"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Brașov"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Brăila"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "București"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Buzău"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Reșița"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Călărași"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Cluj-Napoca"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Constanța"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Sfântu Gheorghe"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Târgoviște"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Craiova"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Galați"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Giurgiu"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Târgu Jiu"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Miercurea Ciuc"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Deva"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Slobozia"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Iași"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Buftea"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Baia Mare"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Drobeta-Turnu Severin"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Târgu Mureș"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Piatra Neamț"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Slatina"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Ploiești"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Satu Mare"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Zalău"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Sibiu"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Suceava"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Alexandria"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Timișoara"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Tulcea"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Vaslui"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Râmnicu Vâlcea"
    });
    listItems2.Add(new SelectListItem
    {
        Text = "Focșani"
    });

}


<head>
    <link href="~/Content/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style>

        body {
            /*background-image: linear-gradient(rgba(0, 142, 99, 0.1), rgba(0, 0, 0, 0.1)), url('../../Content/img_biz/1.jpg');*/
            background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ),url('../../Content/img_biz/1.jpg');
            background-size: cover;
            background-attachment: fixed;
        }

        a:hover {
            text-decoration: none;
        }




        .hovereffect {
            width: 100%;
            height: 275px;
            margin: 10px;
            float: left;
            overflow: hidden;
            position: relative;
            text-align: center;
            cursor: default;
            background:;
        }

        .btn {
            background-color: #47B070;
        }

        .hovereffect .overlay {
            width: 100%;
            height: 100%;
            position: absolute;
            overflow: hidden;
            top: 0;
            background-color: #34b7aa;
            left: 0;
            padding: 50px 10px;
            margin: 20px;
        }

        .hovereffect img {
            display: block;
            position: relative;
            max-width: none;
            height: 100px;
            width: calc(100% + 20px);
            -webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
            transition: opacity 0.35s, transform 0.35s;
            -webkit-transform: translate3d(-10px,0,0);
            transform: translate3d(-10px,0,0);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
        }

        .hovereffect:hover img {
            opacity: 0.4;
            filter: alpha(opacity=40);
            -webkit-transform: translate3d(0,0,0);
            transform: translate3d(0,0,0);
        }

        .hovereffect h4 {
            text-transform: uppercase;
            color: #fff;
            text-align: center;
            position: relative;
            font-size: 17px;
            overflow: hidden;
            padding: 0.5em 0;
            background-color: transparent;
        }

            .hovereffect h4:after {
                position: absolute;
                bottom: 0;
                left: 0;
                width: 100%;
                height: 2px;
                background: #fff;
                content: '';
                -webkit-transition: -webkit-transform 0.35s;
                transition: transform 0.35s;
                -webkit-transform: translate3d(-100%,0,0);
                transform: translate3d(-100%,0,0);
            }

        .hovereffect:hover h4:after {
            -webkit-transform: translate3d(0,0,0);
            transform: translate3d(0,0,0);
        }

        .hovereffect a, .hovereffect p {
            color: #FFF;
            opacity: 0;
            filter: alpha(opacity=0);
            -webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
            transition: opacity 0.35s, transform 0.35s;
            -webkit-transform: translate3d(100%,0,0);
            transform: translate3d(100%,0,0);
        }

        .hovereffect:hover a, .hovereffect:hover p {
            opacity: 1;
            filter: alpha(opacity=100);
            -webkit-transform: translate3d(0,0,0);
            transform: translate3d(0,0,0);
        }


        .dropstil {
            height: 35px;
            border-radius: 8px;
            margin: 8px 0;
            outline: 0;
            width: 200px;
        }


        .center {
            margin: auto;
            position: relative;
            text-align: center;
            top: 50%;
            width: 20%;
        }

        .pagination > li:last-child > a, .pagination > li:last-child > span {
            background-color: #34b7aa;
            border-color: 34b7aa;
        }
        .full{
            width:100%;
        }
    </style>
</head>


<main id="main" style="margin-top:100px">



    <br />


    <section class="content" id="body">

        <br />
        <br />
        <br />


        @using (Html.BeginForm("Index", "Jobs", FormMethod.Get))
        {
        <div class="row">
            <h2 style="margin-left:10%; color:white">Jobs</h2>
            <div class="col-md-12">

                <div class="col-md-1"></div>
                <div class="col-md-2">
                    <input type="text" name="SearchString" class="form-actions dropstil full" value="@ViewData["currentFilter"]" placeholder="Find by Name" />
                </div>

                <div class="col-md-2">
                    <input type="text"  name="experience" class="form-actions dropstil full" @*value="@ViewData["currentFilter"]"*@ placeholder="Find by Experience" />
                </div>

                <div class="col-md-2">
                    @Html.DropDownList("Interest",
                                               new SelectList(ViewBag.Interest, "Interest_ID", "Name"),
                                               "Find by interest",
                                               new { @class = "form-control dropstil full"})
                </div>


                <div class="col-md-2">
                   
                        @Html.DropDownList("Location", listItems2, "-- Select City --", new { @class = "form-control dropstil full" })
                    
                </div>


                <div class=" col-md-2">
                    <input type="submit" value="Search" class="btn btn-default btn-primary" style=" color:white;  width:75px;  margin-top:10px;" />
                    <a href="@Url.Action("Index", "Jobs", new { id = "" })" class="btn btn-default btn-primary " style="color:#fff;width:75px;  margin-top:10px;">Reset</a>
                   
                </div>



                <div class="col-md-1"></div>

            </div>
        </div>
            <br />
            <br />

        }



        <div class="container">
            <div class="row">

                @*@foreach (var item in Model)
                    {
                        <div class="col-lg-2 col-md-3 col-sm-5 col-xs-11">
                            <div class="hovereffect">

                                <div class=" img-responsive" style="height:200px"></div>
                                <div class="overlay" onclick="location.href='@Url.Action("Details", "Jobs", new { id = item.Job_ID })'">

                                    <h4>@item.Name</h4>
                                    <p><a href="@Url.Action("Details", "Jobs", new { id = item.Job_ID })">Detalii</a></p>

                                </div>
                            </div>
                        </div>



                    }*@

                @Html.Partial("JobList")

            </div>

        </div>


        <br />
        <br />
        <br />



        <div class="center" style="color:white">


            @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilter2 = ViewBag.Taguri }))
        </div>




    </section>


</main>

TrueJobs/TrueJobs/Views/Jobs/JobList.cshtml
@model PagedList.IPagedList<TrueJobs.Job>

<style>


    .overlay {
        transition: box-shadow .1s;
    }

        .overlay:hover {
            box-shadow: 0 0 25px rgba(33,33,33,.2);
        }

    .mycont {
        display: block;
        /*margin: 0 auto;*/
        height: 40px;
        line-height: 40px;
        width: 300px;
        padding: 0px 20px 0px 100px;
   
    }

    .mydiv {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        margin-right: 40px;
         display:inline-block;
    }

    i {
        float: left; 
        color: white;
        display: inline-block;
    }

    .my-icon {
        line-height: 40px;
    }
</style>
@foreach (var item in Model)
{

    @*<div class="col-lg-2 col-md-3 col-sm-5 col-xs-11">
            <div class="hovereffect">

                <div class=" img-responsive" style="height:200px"></div>
                <div class="overlay" onclick="location.href='@Url.Action("Details", "Jobs", new { id = item.Job_ID })'">

                    <h4>@item.Name</h4>
                    <p><a href="@Url.Action("Details", "Jobs", new { id = item.Job_ID })">Detalii</a></p>

                </div>
            </div>
        </div>*@
    <br />
    <div class="col-md-12">
        <div class="hovereffect">

            <div class=" img-responsive" style="height:200px"></div>
            <div class="overlay" onclick="location.href='@Url.Action("Details", "Jobs", new { id = item.Job_ID })'">


                <h4>@item.Name</h4>

                <p><a href="@Url.Action("Details", "Jobs", new { id = item.Job_ID })">More details </a></p>
                <br />

                @*<h5 style="position:relative;"><i class="fa fa-user">@item.Company.Name</i>@item.Company.Name</h5>*@

                <div class="mycont">
                    <i class="fa fa-building-o my-icon"></i>
                    <h5 class="mydiv">@item.Company.Name</h5>
                </div>
               
                <div class="mycont">
                    <i class="fa fa-map-marker my-icon"></i>
                    <h5 class="mydiv">@item.Location</h5>
                </div>


            </div>
        </div>
    </div>
    <br />

}